table fact_ausgaben_je_schueler
	lineageTag: 7b61bbeb-adae-45a2-896f-ee7adb3522fc

	column bundesland
		dataType: string
		lineageTag: 34106700-628d-45d0-96a4-21a25777fb40
		summarizeBy: none
		sourceColumn: bundesland

	column jahr
		dataType: int64
		lineageTag: ae95cfb1-9c5e-4cd2-ae71-0df62f0559a6
		summarizeBy: sum
		sourceColumn: jahr

		annotation SummarizationSetBy = Automatic

	column schulart
		dataType: string
		lineageTag: da80c8b1-4beb-49cb-960f-020467a0c44a
		summarizeBy: none
		sourceColumn: schulart

	column ausgaben_je_schueler
		dataType: int64
		lineageTag: 4b6d80f9-0e79-4691-bca7-abec5cf98d76
		summarizeBy: sum
		sourceColumn: ausgaben_je_schueler

		annotation SummarizationSetBy = Automatic

	column region_code
		dataType: string
		lineageTag: 34106700-628d-45d0-96a4-21a25777aaa1
		summarizeBy: none
		sourceColumn: region_code

	partition fact_ausgaben_je_schueler = m
		mode: import
		source =
				let
				kre = Csv.Document(File.Contents(DataFolder & "21111-02-06-4.csv"), [Delimiter=";", Columns=17, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				blrows = Table.SelectRows(kre, each Text.Trim([Column1]) = "2023" and fnEbene([Column2]) = "BL"),
				blmap0 = Table.Distinct(Table.SelectColumns(blrows, {"Column3", "Column2"})),
				blmap = Table.Combine({Table.RenameColumns(blmap0, {{"Column3", "nm"}, {"Column2", "cd"}}), Table.FromRecords({[nm = "Deutschland", cd = "DG"]})}),
				lookupCode = (g as text) as text => let m = Table.SelectRows(blmap, (z) => Text.Trim(z[nm]) = Text.Trim(g)) in if Table.RowCount(m) > 0 then m{0}[cd] else "",
				xls = Excel.Workbook(File.Contents(DataFolder & "21711_ausgaben_je_schueler_2024.xlsx"), null, true),
				sh = xls{[Item = "csv-21711-b01", Kind = "Sheet"]}[Data],
				prom = Table.PromoteHeaders(sh, [PromoteAllScalars=true]),
				sel = Table.SelectRows(prom, each fnToInt([Jahr]) <> null and fnToInt([Ausgaben_je_Schueler]) <> null),
				r = Table.AddColumn(sel, "rec", each [region_code = lookupCode([Gebiet]), bundesland = Text.Trim([Gebiet]), jahr = fnToInt([Jahr]), schulart = "Alle Schularten", ausgaben_je_schueler = fnToInt([Ausgaben_je_Schueler])]),
				tbl = Table.FromRecords(r[rec]),
				typed = Table.TransformColumnTypes(tbl, {{"region_code", type text}, {"bundesland", type text}, {"jahr", Int64.Type}, {"schulart", type text}, {"ausgaben_je_schueler", Int64.Type}}, "en-US")
				in
				typed

